---
title: '**Data Analysis and Visualization Projects**'
geometry: margin=2
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
    includes:
      in_header:
  pdf_document:
    toc: yes
---

<style type="text/css">

div {
color: #170279;
}

#TOC {
  color: #27B789;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #27B789;
  background-color: #4127B7;
}

a:link {
    color: #27B789;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #27B789;

}
a:hover {
color: #27B789;
background-color: #4127B7;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

</style>

Hello, and welcome. This website serves as a place to showcase projects that I have worked on. Working on personal projects is how I apply things that I have learned, and also how I learn new things. Feel free to reuse anything you find here. If you find something that you don't like, or find something that could be done better, and would like to tell me, **[please email me](<mailto:kevinjdswork@gmail.com>)**. New projects are on the horizon, as time permits. Thank you for stopping by.

<div class="row">
  <div class="column">


  </div>
  <div class="column">
  </div>
</div> 


# **Interactive Pallet Tracking Dashboard in R**
* **[Go to the Repository.](https://github.com/kjack89/palletDashboard)**

## Overview

# **Analyzing Webscraped Craigslist Car Ads in Python**
* **[Go to the Repository.](https://github.com/kjack89/palletDashboard)**

## Overview

# **Another Project Coming Soon**
* **[Go to the Repository.](https://github.com/kjack89/palletDashboard)**

## Overview

This page was last updated on `r Sys.time()` Eastern Time.
